create table if not exists public.admin_search_jobs (
  id bigint generated by default as identity primary key,
  query text not null,
  city text not null,
  max_results integer not null default 10 check (max_results between 1 and 30),
  deep_research boolean not null default true,
  ai_mode text not null default 'smart' check (ai_mode in ('smart', 'flash', 'pro')),
  status text not null default 'queued' check (status in ('queued', 'running', 'success', 'failed')),
  created_by text,
  estimated_tokens integer not null default 0,
  estimated_cost_usd numeric not null default 0,
  result jsonb not null default '{}'::jsonb,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_search_jobs_status_idx
  on public.admin_search_jobs (status, created_at desc);

create table if not exists public.ai_token_ledger (
  id bigint generated by default as identity primary key,
  job_id bigint references public.admin_search_jobs(id) on delete set null,
  kind text not null default 'usage',
  provider text not null default 'deepseek',
  model text,
  estimated_tokens integer not null default 0,
  actual_tokens integer,
  estimated_cost_usd numeric not null default 0,
  actual_cost_usd numeric,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_token_ledger_job_idx
  on public.ai_token_ledger (job_id, created_at desc);

do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select conname
    from pg_constraint
    where conrelid = 'public.leads'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%status%'
  loop
    execute format('alter table public.leads drop constraint if exists %I', constraint_name);
  end loop;
end $$;

alter table public.leads
  alter column status set default 'yeni';

alter table public.leads
  add constraint leads_status_check
  check (status in ('yeni', 'ready', 'missing_info', 'contacted', 'follow_up', 'converted', 'lost'));

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  role text not null default 'sales' check (role in ('admin', 'sales')),
  title text,
  avatar_url text,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.app_users
  add column if not exists title text,
  add column if not exists avatar_url text;

create index if not exists app_users_role_idx
  on public.app_users (role, active);

create table if not exists public.lead_assignments (
  id bigint generated by default as identity primary key,
  lead_name text not null references public.leads(name) on delete cascade,
  user_email text not null references public.app_users(email) on delete cascade,
  status text not null default 'active' check (status in ('active', 'done', 'snoozed', 'archived')),
  due_at timestamptz,
  assigned_by text,
  assigned_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb,
  unique (lead_name, user_email)
);

create index if not exists lead_assignments_user_idx
  on public.lead_assignments (user_email, status, due_at);

create index if not exists lead_assignments_lead_idx
  on public.lead_assignments (lead_name, status);

alter table public.admin_search_jobs enable row level security;
alter table public.ai_token_ledger enable row level security;
alter table public.app_users enable row level security;
alter table public.lead_assignments enable row level security;

grant select, insert, update, delete on public.admin_search_jobs to service_role;
grant select, insert, update, delete on public.ai_token_ledger to service_role;
grant select, insert, update, delete on public.app_users to service_role;
grant select, insert, update, delete on public.lead_assignments to service_role;

grant usage, select on sequence public.admin_search_jobs_id_seq to service_role;
grant usage, select on sequence public.ai_token_ledger_id_seq to service_role;
grant usage, select on sequence public.app_users_id_seq to service_role;
grant usage, select on sequence public.lead_assignments_id_seq to service_role;

delete from public.outreach_events where id > 0;

update public.leads
set status = 'yeni',
    updated_at = now()
where status is distinct from 'yeni';

update public.lead_assignments
set status = 'archived',
    updated_at = now()
where status = 'active';
