-- Zeplin Lead System - Supabase Free Plan schema
-- Run this in Supabase SQL Editor once per project.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  external_id text not null unique,
  name text not null unique,
  sector text,
  city text,
  category text,
  phone text,
  address text,
  rating numeric,
  review_count integer,
  maps_url text,
  website_url text,
  instagram_url text,
  score integer check (score between 0 and 100),
  grade text check (grade in ('A', 'B', 'C', 'D')),
  estimated_value_tl integer default 0,
  sales_priority_score integer check (sales_priority_score between 0 and 100),
  next_action text,
  priority_reason text,
  recommended_package jsonb not null default '{}'::jsonb,
  matched_services jsonb not null default '[]'::jsonb,
  data_quality jsonb not null default '{}'::jsonb,
  research_brief text,
  ai_report text,
  ai_email text,
  status text not null default 'yeni' check (status in ('yeni', 'ready', 'missing_info', 'contacted', 'follow_up', 'converted', 'lost')),
  last_analyzed text,
  raw jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_priority_idx on public.leads (sales_priority_score desc);
create index if not exists leads_score_idx on public.leads (score asc);
create index if not exists leads_sector_idx on public.leads (sector);
create index if not exists leads_status_idx on public.leads (status);
create index if not exists leads_raw_gin_idx on public.leads using gin (raw);

create table if not exists public.outreach_events (
  id bigint generated by default as identity primary key,
  lead_name text not null references public.leads(name) on delete cascade,
  action text not null,
  note text,
  actor_email text,
  source text not null default 'dashboard',
  idempotency_key text unique,
  happened_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists outreach_events_lead_idx on public.outreach_events (lead_name, happened_at desc);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_email text,
  event_type text not null,
  target_type text not null,
  target_key text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.auth_login_attempts (
  id bigint generated by default as identity primary key,
  key_hash text not null,
  attempted_at timestamptz not null default now()
);

create table if not exists public.ai_generations (
  id bigint generated by default as identity primary key,
  cache_key text not null unique,
  task text not null,
  provider text not null,
  model text not null,
  content text not null,
  usage jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pipeline_runs (
  id bigint generated by default as identity primary key,
  kind text not null,
  status text not null,
  message text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_search_jobs (
  id bigint generated by default as identity primary key,
  query text not null,
  city text not null,
  max_results integer not null default 10 check (max_results between 1 and 30),
  deep_research boolean not null default true,
  ai_mode text not null default 'smart' check (ai_mode in ('smart', 'flash', 'pro')),
  status text not null default 'queued' check (status in ('queued', 'running', 'success', 'partial_success', 'failed')),
  created_by text,
  estimated_tokens integer not null default 0,
  estimated_cost_usd numeric not null default 0,
  result jsonb not null default '{}'::jsonb,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_search_jobs_status_idx
  on public.admin_search_jobs (status, created_at desc);

create table if not exists public.ai_token_ledger (
  id bigint generated by default as identity primary key,
  job_id bigint references public.admin_search_jobs(id) on delete set null,
  kind text not null default 'usage',
  provider text not null default 'deepseek',
  model text,
  estimated_tokens integer not null default 0,
  actual_tokens integer,
  estimated_cost_usd numeric not null default 0,
  actual_cost_usd numeric,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_token_ledger_job_idx
  on public.ai_token_ledger (job_id, created_at desc);

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  role text not null default 'sales' check (role in ('admin', 'sales')),
  title text,
  avatar_url text,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists app_users_role_idx
  on public.app_users (role, active);

create table if not exists public.lead_assignments (
  id bigint generated by default as identity primary key,
  lead_name text not null references public.leads(name) on delete cascade,
  user_email text not null references public.app_users(email) on delete cascade,
  status text not null default 'active' check (status in ('active', 'done', 'snoozed', 'archived')),
  due_at timestamptz,
  assigned_by text,
  assigned_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb,
  unique (lead_name, user_email)
);

create index if not exists lead_assignments_user_idx
  on public.lead_assignments (user_email, status, due_at);

create index if not exists lead_assignments_lead_idx
  on public.lead_assignments (lead_name, status);

alter table public.leads enable row level security;
alter table public.outreach_events enable row level security;
alter table public.pipeline_runs enable row level security;
alter table public.admin_search_jobs enable row level security;
alter table public.ai_token_ledger enable row level security;
alter table public.app_users enable row level security;
alter table public.lead_assignments enable row level security;
alter table public.audit_events enable row level security;
alter table public.auth_login_attempts enable row level security;
alter table public.ai_generations enable row level security;

grant usage on schema public to service_role;

grant select, insert, update, delete on public.leads to service_role;
grant select, insert, update, delete on public.outreach_events to service_role;
grant select, insert, update, delete on public.pipeline_runs to service_role;
grant select, insert, update, delete on public.admin_search_jobs to service_role;
grant select, insert, update, delete on public.ai_token_ledger to service_role;
grant select, insert, update, delete on public.app_users to service_role;
grant select, insert, update, delete on public.lead_assignments to service_role;
grant select, insert on public.audit_events to service_role;
grant select, insert, delete on public.auth_login_attempts to service_role;
grant select, insert, update, delete on public.ai_generations to service_role;

grant usage, select on sequence public.leads_id_seq to service_role;
grant usage, select on sequence public.outreach_events_id_seq to service_role;
grant usage, select on sequence public.pipeline_runs_id_seq to service_role;
grant usage, select on sequence public.admin_search_jobs_id_seq to service_role;
grant usage, select on sequence public.ai_token_ledger_id_seq to service_role;
grant usage, select on sequence public.app_users_id_seq to service_role;
grant usage, select on sequence public.lead_assignments_id_seq to service_role;
grant usage, select on sequence public.audit_events_id_seq to service_role;
grant usage, select on sequence public.auth_login_attempts_id_seq to service_role;
grant usage, select on sequence public.ai_generations_id_seq to service_role;

-- Service-role/secret-key backend sync bypasses RLS. Add anon policies later
-- only when the browser dashboard should read/write directly from Supabase.
