-- Zeplin Lead System - full database schema.
--
-- GENERATED by scripts/build_schema.py from supabase/migrations. Do not edit
-- this file; add a new numbered migration and rebuild instead.
--
-- Fresh project: run this whole file once in the Supabase SQL editor.
-- Existing project: run the migrations you have not applied yet, in order.
-- Every statement is idempotent, so re-running is safe.

-- ===== 001_initial_schema.sql =====

-- Original Zeplin Lead System schema (commit 77e3843, May 2026).
-- Kept so the migration chain 001..N can build a database from scratch and
-- so upgrades can be tested from the very first deployed shape.


create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sector text,
  city text,
  category text,
  phone text,
  address text,
  rating numeric,
  review_count integer,
  maps_url text,
  website_url text,
  instagram_url text,
  score integer check (score between 0 and 100),
  grade text check (grade in ('A', 'B', 'C', 'D')),
  estimated_value_tl integer default 0,
  sales_priority_score integer check (sales_priority_score between 0 and 100),
  next_action text,
  priority_reason text,
  recommended_package jsonb not null default '{}'::jsonb,
  matched_services jsonb not null default '[]'::jsonb,
  data_quality jsonb not null default '{}'::jsonb,
  research_brief text,
  ai_report text,
  ai_email text,
  status text not null default 'yeni' check (status in ('yeni', 'contacted', 'converted')),
  last_analyzed text,
  raw jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_priority_idx on public.leads (sales_priority_score desc);
create index if not exists leads_score_idx on public.leads (score asc);
create index if not exists leads_sector_idx on public.leads (sector);
create index if not exists leads_status_idx on public.leads (status);
create index if not exists leads_raw_gin_idx on public.leads using gin (raw);

create table if not exists public.outreach_events (
  id bigint generated by default as identity primary key,
  lead_name text not null references public.leads(name) on delete cascade,
  action text not null,
  note text,
  happened_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists outreach_events_lead_idx on public.outreach_events (lead_name, happened_at desc);

create table if not exists public.pipeline_runs (
  id bigint generated by default as identity primary key,
  kind text not null,
  status text not null,
  message text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;
alter table public.outreach_events enable row level security;
alter table public.pipeline_runs enable row level security;

-- Service-role/secret-key backend sync bypasses RLS. Add anon policies later
-- only when the browser dashboard should read/write directly from Supabase.

-- ===== 002_status.sql =====

alter table public.leads
  add column if not exists status text not null default 'yeni'
  check (status in ('yeni', 'contacted', 'converted'));

create index if not exists leads_status_idx on public.leads (status);

-- ===== 003_admin_search.sql =====

create table if not exists public.admin_search_jobs (
  id bigint generated by default as identity primary key,
  query text not null,
  city text not null,
  max_results integer not null default 10 check (max_results between 1 and 30),
  deep_research boolean not null default true,
  ai_mode text not null default 'smart' check (ai_mode in ('smart', 'flash', 'pro')),
  status text not null default 'queued' check (status in ('queued', 'running', 'success', 'failed')),
  created_by text,
  estimated_tokens integer not null default 0,
  estimated_cost_usd numeric not null default 0,
  result jsonb not null default '{}'::jsonb,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_search_jobs_status_idx
  on public.admin_search_jobs (status, created_at desc);

create table if not exists public.ai_token_ledger (
  id bigint generated by default as identity primary key,
  job_id bigint references public.admin_search_jobs(id) on delete set null,
  kind text not null default 'usage',
  provider text not null default 'deepseek',
  model text,
  estimated_tokens integer not null default 0,
  actual_tokens integer,
  estimated_cost_usd numeric not null default 0,
  actual_cost_usd numeric,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_token_ledger_job_idx
  on public.ai_token_ledger (job_id, created_at desc);

alter table public.admin_search_jobs enable row level security;
alter table public.ai_token_ledger enable row level security;

grant select, insert, update, delete on public.admin_search_jobs to service_role;
grant select, insert, update, delete on public.ai_token_ledger to service_role;

grant usage, select on sequence public.admin_search_jobs_id_seq to service_role;
grant usage, select on sequence public.ai_token_ledger_id_seq to service_role;

-- ===== 004_roles_assignments.sql =====

do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select conname
    from pg_constraint
    where conrelid = 'public.leads'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%status%'
  loop
    execute format('alter table public.leads drop constraint if exists %I', constraint_name);
  end loop;
end $$;

alter table public.leads
  alter column status set default 'yeni';

alter table public.leads
  add constraint leads_status_check
  check (status in ('yeni', 'ready', 'missing_info', 'contacted', 'follow_up', 'converted', 'lost'));

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  role text not null default 'sales' check (role in ('admin', 'sales')),
  title text,
  avatar_url text,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists app_users_role_idx
  on public.app_users (role, active);

create table if not exists public.lead_assignments (
  id bigint generated by default as identity primary key,
  lead_name text not null references public.leads(name) on delete cascade,
  user_email text not null references public.app_users(email) on delete cascade,
  status text not null default 'active' check (status in ('active', 'done', 'snoozed', 'archived')),
  due_at timestamptz,
  assigned_by text,
  assigned_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb,
  unique (lead_name, user_email)
);

create index if not exists lead_assignments_user_idx
  on public.lead_assignments (user_email, status, due_at);

create index if not exists lead_assignments_lead_idx
  on public.lead_assignments (lead_name, status);

alter table public.app_users enable row level security;
alter table public.lead_assignments enable row level security;

grant select, insert, update, delete on public.app_users to service_role;
grant select, insert, update, delete on public.lead_assignments to service_role;

grant usage, select on sequence public.app_users_id_seq to service_role;
grant usage, select on sequence public.lead_assignments_id_seq to service_role;

-- ===== 005_team_profiles.sql =====

alter table if exists public.app_users
  add column if not exists title text,
  add column if not exists avatar_url text;

-- ===== 006_security_crm_hardening.sql =====

-- Security, CRM ownership, idempotency and durable worker primitives.
-- Safe to run repeatedly in the Supabase SQL editor.

create extension if not exists pgcrypto;

alter table public.leads add column if not exists external_id text;

update public.leads
set external_id = case
  when coalesce(maps_url, raw->>'maps_url', '') <> ''
    then 'maps:' || encode(digest(coalesce(maps_url, raw->>'maps_url'), 'sha256'), 'hex')
  else 'name:' || encode(
    digest(lower(trim(name)) || '|' || lower(trim(coalesce(city, ''))), 'sha256'),
    'hex'
  )
end
where external_id is null;

alter table public.leads alter column external_id set not null;
create unique index if not exists leads_external_id_uidx on public.leads (external_id);

alter table public.outreach_events
  add column if not exists actor_email text,
  add column if not exists source text not null default 'dashboard',
  add column if not exists idempotency_key text;

create unique index if not exists outreach_events_idempotency_uidx
  on public.outreach_events (idempotency_key)
  where idempotency_key is not null;

create index if not exists outreach_events_actor_idx
  on public.outreach_events (actor_email, happened_at desc);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_email text,
  event_type text not null,
  target_type text not null,
  target_key text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_events_actor_idx
  on public.audit_events (actor_email, created_at desc);
create index if not exists audit_events_target_idx
  on public.audit_events (target_type, target_key, created_at desc);
alter table public.audit_events enable row level security;
grant select, insert on public.audit_events to service_role;
grant usage, select on sequence public.audit_events_id_seq to service_role;

create table if not exists public.auth_login_attempts (
  id bigint generated by default as identity primary key,
  key_hash text not null,
  attempted_at timestamptz not null default now()
);

create index if not exists auth_login_attempts_key_idx
  on public.auth_login_attempts (key_hash, attempted_at desc);
alter table public.auth_login_attempts enable row level security;
grant select, insert, delete on public.auth_login_attempts to service_role;
grant usage, select on sequence public.auth_login_attempts_id_seq to service_role;

create table if not exists public.ai_generations (
  id bigint generated by default as identity primary key,
  cache_key text not null unique,
  task text not null,
  provider text not null,
  model text not null,
  content text not null,
  usage jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ai_generations enable row level security;
grant select, insert, update, delete on public.ai_generations to service_role;
grant usage, select on sequence public.ai_generations_id_seq to service_role;

-- There can be only one current owner for a lead.
with ranked as (
  select id, row_number() over (
    partition by lead_name
    order by updated_at desc nulls last, id desc
  ) as position
  from public.lead_assignments
  where status = 'active'
)
update public.lead_assignments assignment
set status = 'archived', updated_at = now()
from ranked
where assignment.id = ranked.id and ranked.position > 1;

create unique index if not exists lead_assignments_one_active_owner_uidx
  on public.lead_assignments (lead_name)
  where status = 'active';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists ai_generations_set_updated_at on public.ai_generations;
create trigger ai_generations_set_updated_at before update on public.ai_generations
for each row execute function public.set_updated_at();

drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at before update on public.leads
for each row execute function public.set_updated_at();

drop trigger if exists app_users_set_updated_at on public.app_users;
create trigger app_users_set_updated_at before update on public.app_users
for each row execute function public.set_updated_at();

drop trigger if exists lead_assignments_set_updated_at on public.lead_assignments;
create trigger lead_assignments_set_updated_at before update on public.lead_assignments
for each row execute function public.set_updated_at();

drop trigger if exists admin_search_jobs_set_updated_at on public.admin_search_jobs;
create trigger admin_search_jobs_set_updated_at before update on public.admin_search_jobs
for each row execute function public.set_updated_at();

create or replace function public.create_admin_search_job(
  query text,
  city text,
  max_results integer,
  deep_research boolean,
  ai_mode text,
  created_by text,
  estimated_tokens integer,
  estimated_cost_usd numeric,
  reservation_meta jsonb default '{}'::jsonb
)
returns setof public.admin_search_jobs
language plpgsql
security definer
set search_path = public
as $$
#variable_conflict use_variable
declare
  created_job public.admin_search_jobs;
begin
  insert into public.admin_search_jobs (
    query, city, max_results, deep_research, ai_mode, created_by,
    estimated_tokens, estimated_cost_usd, meta
  ) values (
    query, city, max_results, deep_research, ai_mode, created_by,
    estimated_tokens, estimated_cost_usd, reservation_meta
  ) returning * into created_job;

  insert into public.ai_token_ledger (
    job_id, kind, provider, model, estimated_tokens, estimated_cost_usd, meta
  ) values (
    created_job.id, 'reservation', 'deepseek',
    reservation_meta->>'model_mix', estimated_tokens, estimated_cost_usd,
    jsonb_build_object('query', query, 'city', city, 'max_results', max_results)
  );

  return next created_job;
end;
$$;

create or replace function public.assign_lead_owner(
  target_lead_name text,
  target_user_email text,
  assignment_due_at timestamptz,
  assignment_by text,
  assignment_status text,
  assignment_meta jsonb default '{}'::jsonb
)
returns setof public.lead_assignments
language plpgsql
security definer
set search_path = public
as $$
declare
  assigned public.lead_assignments;
begin
  if assignment_status = 'active' then
    update public.lead_assignments
    set status = 'archived', updated_at = now()
    where lead_name = target_lead_name
      and status = 'active'
      and user_email <> lower(target_user_email);
  end if;

  insert into public.lead_assignments (
    lead_name, user_email, due_at, assigned_by, status, meta
  ) values (
    target_lead_name, lower(target_user_email), assignment_due_at,
    lower(assignment_by), assignment_status, assignment_meta
  )
  on conflict (lead_name, user_email) do update
  set due_at = excluded.due_at,
      assigned_by = excluded.assigned_by,
      status = excluded.status,
      meta = excluded.meta,
      updated_at = now()
  returning * into assigned;

  return next assigned;
end;
$$;

create or replace function public.claim_admin_search_jobs(job_limit integer default 1)
returns setof public.admin_search_jobs
language plpgsql
security definer
set search_path = public
as $$
begin
  -- A crashed worker may leave a job running. Retry it after one hour.
  update public.admin_search_jobs
  set status = 'queued',
      result = coalesce(result, '{}'::jsonb) || jsonb_build_object('recovered_at', now())
  where status = 'running' and updated_at < now() - interval '1 hour';

  return query
  with candidates as (
    select id
    from public.admin_search_jobs
    where status = 'queued'
    order by created_at asc
    for update skip locked
    limit greatest(1, least(job_limit, 10))
  )
  update public.admin_search_jobs jobs
  set status = 'running',
      result = coalesce(jobs.result, '{}'::jsonb) || jsonb_build_object('started_at', now())
  from candidates
  where jobs.id = candidates.id
  returning jobs.*;
end;
$$;

create or replace function public.check_login_rate_limit(
  attempt_key_hash text,
  attempt_limit integer default 8,
  window_seconds integer default 900
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  recent_attempts integer;
begin
  delete from public.auth_login_attempts
  where attempted_at < now() - interval '1 day';

  select count(*) into recent_attempts
  from public.auth_login_attempts
  where key_hash = attempt_key_hash
    and attempted_at >= now() - make_interval(secs => greatest(60, window_seconds));

  return recent_attempts >= greatest(1, attempt_limit);
end;
$$;

create or replace function public.record_login_attempt(
  attempt_key_hash text,
  attempt_succeeded boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if attempt_succeeded then
    delete from public.auth_login_attempts where key_hash = attempt_key_hash;
  else
    insert into public.auth_login_attempts (key_hash) values (attempt_key_hash);
  end if;
end;
$$;

revoke all on function public.create_admin_search_job(
  text, text, integer, boolean, text, text, integer, numeric, jsonb
) from public, anon, authenticated;
revoke all on function public.claim_admin_search_jobs(integer)
  from public, anon, authenticated;
grant execute on function public.create_admin_search_job(
  text, text, integer, boolean, text, text, integer, numeric, jsonb
) to service_role;
grant execute on function public.claim_admin_search_jobs(integer) to service_role;
revoke all on function public.assign_lead_owner(
  text, text, timestamptz, text, text, jsonb
) from public, anon, authenticated;
grant execute on function public.assign_lead_owner(
  text, text, timestamptz, text, text, jsonb
) to service_role;
revoke all on function public.check_login_rate_limit(text, integer, integer)
  from public, anon, authenticated;
revoke all on function public.record_login_attempt(text, boolean)
  from public, anon, authenticated;
grant execute on function public.check_login_rate_limit(text, integer, integer)
  to service_role;
grant execute on function public.record_login_attempt(text, boolean)
  to service_role;

-- ===== 007_sales_workspace.sql =====

-- Optional native columns for structured contact results.
-- The application is backward compatible and also reads versioned JSON notes,
-- so this migration can be applied without downtime.

alter table public.outreach_events
  add column if not exists channel text,
  add column if not exists outcome text,
  add column if not exists follow_up_at timestamptz,
  add column if not exists service_slugs text[] not null default '{}',
  add column if not exists contact_name text;

create index if not exists outreach_events_follow_up_idx
  on public.outreach_events (follow_up_at)
  where follow_up_at is not null;

create index if not exists outreach_events_outcome_idx
  on public.outreach_events (outcome, happened_at desc)
  where outcome is not null;

-- ===== 008_lead_identity_expand.sql =====

-- Stable lead identity (expand phase), idempotency repair and schema readiness.
--
-- Safe to run repeatedly. Nothing here removes the name-based columns or the
-- unique(name) constraint: the application keeps reading and writing lead_name,
-- and triggers keep the new lead_id columns in step. Contract steps (NOT NULL,
-- dropping unique(name)) come in a later migration once the app uses lead_id.

create table if not exists public.schema_migrations (
  version text primary key,
  applied_at timestamptz not null default now()
);
alter table public.schema_migrations enable row level security;
grant select on public.schema_migrations to service_role;

-- The original tables only got service_role grants from later schema.sql
-- snapshots, never from a migration. Make every path end up the same.
grant select, insert, update, delete on public.leads to service_role;
grant select, insert, update, delete on public.outreach_events to service_role;
grant select, insert, update, delete on public.pipeline_runs to service_role;
grant usage, select on sequence public.leads_id_seq to service_role;
grant usage, select on sequence public.outreach_events_id_seq to service_role;
grant usage, select on sequence public.pipeline_runs_id_seq to service_role;

-- PostgREST sends `ON CONFLICT (idempotency_key)`. Postgres cannot infer the
-- partial unique index from migration 006 for that clause, so databases built
-- from migrations rejected every idempotent insert. A plain unique constraint
-- (NULLs stay allowed) works on every path.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.outreach_events'::regclass
      and conname = 'outreach_events_idempotency_key_key'
  ) then
    alter table public.outreach_events
      add constraint outreach_events_idempotency_key_key unique (idempotency_key);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.leads'::regclass
      and conname = 'leads_external_id_key'
  ) then
    alter table public.leads add constraint leads_external_id_key unique (external_id);
  end if;
end $$;
drop index if exists public.outreach_events_idempotency_uidx;
drop index if exists public.leads_external_id_uidx;

-- Renaming a lead must not break its history. Recreate the name foreign keys
-- with ON UPDATE CASCADE (they already cascade on delete).
do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'outreach_events_lead_name_fkey' and confupdtype <> 'c'
  ) then
    alter table public.outreach_events drop constraint outreach_events_lead_name_fkey;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'outreach_events_lead_name_fkey') then
    alter table public.outreach_events
      add constraint outreach_events_lead_name_fkey foreign key (lead_name)
      references public.leads(name) on update cascade on delete cascade;
  end if;
  if exists (
    select 1 from pg_constraint
    where conname = 'lead_assignments_lead_name_fkey' and confupdtype <> 'c'
  ) then
    alter table public.lead_assignments drop constraint lead_assignments_lead_name_fkey;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'lead_assignments_lead_name_fkey') then
    alter table public.lead_assignments
      add constraint lead_assignments_lead_name_fkey foreign key (lead_name)
      references public.leads(name) on update cascade on delete cascade;
  end if;
end $$;

-- lead_id: the identity that survives renames and same-name branches.
alter table public.outreach_events add column if not exists lead_id bigint;
alter table public.lead_assignments add column if not exists lead_id bigint;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'outreach_events_lead_id_fkey') then
    alter table public.outreach_events
      add constraint outreach_events_lead_id_fkey foreign key (lead_id)
      references public.leads(id) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'lead_assignments_lead_id_fkey') then
    alter table public.lead_assignments
      add constraint lead_assignments_lead_id_fkey foreign key (lead_id)
      references public.leads(id) on delete cascade;
  end if;
end $$;

update public.outreach_events event
set lead_id = lead.id
from public.leads lead
where event.lead_id is null and lead.name = event.lead_name;

update public.lead_assignments assignment
set lead_id = lead.id
from public.leads lead
where assignment.lead_id is null and lead.name = assignment.lead_name;

create index if not exists outreach_events_lead_id_idx
  on public.outreach_events (lead_id, happened_at desc);
create index if not exists lead_assignments_lead_id_idx
  on public.lead_assignments (lead_id, status);

-- While the application writes lead_name only, derive lead_id from it.
create or replace function public.fill_lead_id_from_name()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.lead_name is not null and (
    (tg_op = 'INSERT' and new.lead_id is null)
    or (tg_op = 'UPDATE' and new.lead_name is distinct from old.lead_name and new.lead_id is not distinct from old.lead_id)
  ) then
    select id into new.lead_id from public.leads where name = new.lead_name;
  end if;
  return new;
end;
$$;

drop trigger if exists outreach_events_fill_lead_id on public.outreach_events;
create trigger outreach_events_fill_lead_id
before insert or update on public.outreach_events
for each row execute function public.fill_lead_id_from_name();

drop trigger if exists lead_assignments_fill_lead_id on public.lead_assignments;
create trigger lead_assignments_fill_lead_id
before insert or update on public.lead_assignments
for each row execute function public.fill_lead_id_from_name();

-- External identities. A provider id belongs to exactly one lead.
create table if not exists public.lead_sources (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  provider text not null check (provider in ('google_places')),
  provider_id text not null,
  url text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (provider, provider_id)
);
create index if not exists lead_sources_lead_idx on public.lead_sources (lead_id);
alter table public.lead_sources enable row level security;
grant select, insert, update, delete on public.lead_sources to service_role;
grant usage, select on sequence public.lead_sources_id_seq to service_role;

-- Google place id: the verified Places API result first, else the id embedded
-- in a Google Maps URL (".../data=...!19sChIJ...").
create or replace function public.lead_google_place_id(maps_url text, raw jsonb)
returns text
language sql
immutable
set search_path = public
as $$
  select coalesce(
    case
      when raw #>> '{research,google_places,status}' = 'verified'
        then nullif(raw #>> '{research,google_places,place_id}', '')
    end,
    substring(coalesce(maps_url, raw ->> 'maps_url', '') from '!19s([A-Za-z0-9_-]{10,})')
  );
$$;

-- Record the provider id when a lead is written. If the id already belongs to
-- another lead, nothing is merged: scripts/lead_identity_report.py lists it.
create or replace function public.record_lead_source()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  place_id text := public.lead_google_place_id(new.maps_url, new.raw);
begin
  if place_id is not null then
    insert into public.lead_sources (lead_id, provider, provider_id, url)
    values (new.id, 'google_places', place_id, new.maps_url)
    on conflict (provider, provider_id) do update
      set last_seen_at = now(), url = coalesce(excluded.url, lead_sources.url)
      where lead_sources.lead_id = excluded.lead_id;
  end if;
  return new;
end;
$$;

drop trigger if exists leads_record_source on public.leads;
create trigger leads_record_source
after insert or update of maps_url, raw on public.leads
for each row execute function public.record_lead_source();

-- Backfill only unambiguous ids; shared ids are left for manual review.
insert into public.lead_sources (lead_id, provider, provider_id, url)
select min(lead.id), 'google_places', candidate.place_id, min(lead.maps_url)
from public.leads lead
cross join lateral (select public.lead_google_place_id(lead.maps_url, lead.raw) as place_id) candidate
where candidate.place_id is not null
group by candidate.place_id
having count(*) = 1
on conflict (provider, provider_id) do nothing;

-- One call that tells the API whether this database can serve it.
create or replace function public.schema_readiness()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'version', (select max(version) from public.schema_migrations),
    'checks', jsonb_build_object(
      'assign_lead_owner', to_regprocedure('public.assign_lead_owner(text,text,timestamptz,text,text,jsonb)') is not null,
      'claim_admin_search_jobs', to_regprocedure('public.claim_admin_search_jobs(integer)') is not null,
      'create_admin_search_job', to_regprocedure('public.create_admin_search_job(text,text,integer,boolean,text,text,integer,numeric,jsonb)') is not null,
      'check_login_rate_limit', to_regprocedure('public.check_login_rate_limit(text,integer,integer)') is not null,
      'record_login_attempt', to_regprocedure('public.record_login_attempt(text,boolean)') is not null,
      'one_active_owner_index', to_regclass('public.lead_assignments_one_active_owner_uidx') is not null,
      'idempotency_constraint', exists (
        select 1 from pg_constraint
        where conrelid = 'public.outreach_events'::regclass
          and conname = 'outreach_events_idempotency_key_key'
      ),
      'structured_outreach_columns', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'outreach_events' and column_name = 'follow_up_at'
      ),
      'lead_id_columns', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'lead_assignments' and column_name = 'lead_id'
      ),
      'lead_sources', to_regclass('public.lead_sources') is not null
    )
  );
$$;
revoke all on function public.schema_readiness() from public, anon, authenticated;
grant execute on function public.schema_readiness() to service_role;

insert into public.schema_migrations (version) values ('008') on conflict do nothing;

-- ===== 009_contact_result_command.sql =====

-- Contact results recorded as one transaction, with real idempotency.
--
-- Safe to run repeatedly and safe for the previous application version: it only
-- adds a column, a table, triggers and functions. Apply it before deploying code
-- that calls record_contact_result.

-- CRM revision of a lead. The contact command bumps it; any other status change
-- (pipeline drag, /api/status) bumps it through the trigger.
alter table public.leads add column if not exists revision integer not null default 0;

create or replace function public.bump_lead_revision()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.status is distinct from old.status and new.revision = old.revision then
    new.revision := old.revision + 1;
  end if;
  return new;
end;
$$;

create or replace trigger leads_bump_revision
before update on public.leads
for each row execute function public.bump_lead_revision();

-- One row per logical submission. A retry with the same key gets the stored
-- response instead of running the command again; the same key with another
-- payload is rejected.
create table if not exists public.command_requests (
  idempotency_key text primary key,
  command text not null,
  actor_email text not null,
  request_hash text not null,
  response jsonb not null,
  created_at timestamptz not null default now()
);
create index if not exists command_requests_created_idx on public.command_requests (created_at);
alter table public.command_requests enable row level security;
grant select, insert, delete on public.command_requests to service_role;

-- Business rules (validation, default follow-up date, status per outcome) live
-- in src/activity.py; this function applies them atomically and re-checks
-- ownership inside the transaction. Errors use PostgREST's PTxxx codes so the
-- HTTP status is meaningful: PT400 bad input, PT403 not the owner, PT404 no
-- such lead, PT409 stale revision or reused idempotency key.
create or replace function public.record_contact_result(
  p_idempotency_key text,
  p_request_hash text,
  p_actor_email text,
  p_actor_is_admin boolean,
  p_lead_name text,
  p_expected_revision integer,
  p_channel text,
  p_outcome text,
  p_follow_up_at timestamptz,
  p_service_slugs text[],
  p_contact_name text,
  p_note text,
  p_lead_status text,
  p_assignment_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  previous public.command_requests;
  target public.leads;
  owner_row public.lead_assignments;
  new_event_id bigint;
  new_revision integer;
  happened timestamptz := now();
  assignment_due timestamptz;
  result jsonb;
begin
  if coalesce(length(p_idempotency_key), 0) < 16 or coalesce(p_request_hash, '') = '' then
    raise exception using errcode = 'PT400', message = 'IDEMPOTENCY_KEY_REQUIRED';
  end if;
  if p_assignment_status not in ('active', 'done') then
    raise exception using errcode = 'PT400', message = 'ASSIGNMENT_STATUS_INVALID';
  end if;

  -- Two concurrent submissions with one key run one after the other.
  perform pg_advisory_xact_lock(hashtext('record_contact_result:' || p_idempotency_key));
  select * into previous from public.command_requests where idempotency_key = p_idempotency_key;
  if found then
    if previous.command <> 'record_contact_result'
       or previous.request_hash <> p_request_hash
       or lower(previous.actor_email) <> lower(p_actor_email) then
      raise exception using errcode = 'PT409', message = 'IDEMPOTENCY_KEY_REUSED';
    end if;
    return previous.response || jsonb_build_object('replayed', true);
  end if;

  select * into target from public.leads where name = p_lead_name for update;
  if not found then
    raise exception using errcode = 'PT404', message = 'LEAD_NOT_FOUND';
  end if;

  select * into owner_row
  from public.lead_assignments
  where lead_name = target.name and status = 'active'
  for update;
  if not p_actor_is_admin and (owner_row.id is null or lower(owner_row.user_email) <> lower(p_actor_email)) then
    raise exception using errcode = 'PT403', message = 'LEAD_NOT_ASSIGNED';
  end if;

  if p_expected_revision is not null and p_expected_revision <> target.revision then
    raise exception using errcode = 'PT409', message = 'LEAD_VERSION_CONFLICT';
  end if;

  insert into public.outreach_events (
    lead_name, lead_id, action, note, happened_at, actor_email, source, idempotency_key,
    channel, outcome, follow_up_at, service_slugs, contact_name
  )
  values (
    target.name, target.id, 'contact_result_recorded', p_note, happened, lower(p_actor_email),
    'dashboard', p_idempotency_key, p_channel, p_outcome, p_follow_up_at,
    coalesce(p_service_slugs, '{}'), p_contact_name
  )
  returning id into new_event_id;

  update public.leads
  set status = p_lead_status, revision = revision + 1, updated_at = happened
  where id = target.id
  returning revision into new_revision;

  -- Closing the lead closes its follow-up; otherwise the owner gets the new date.
  assignment_due := case when p_assignment_status = 'done' then null else p_follow_up_at end;
  if owner_row.id is not null then
    update public.lead_assignments
    set status = p_assignment_status,
        due_at = assignment_due,
        updated_at = happened,
        meta = coalesce(meta, '{}'::jsonb) || jsonb_build_object(
          'last_outcome', p_outcome,
          'last_channel', p_channel,
          'last_contact_at', happened,
          'follow_up_at', assignment_due,
          'service_slugs', to_jsonb(coalesce(p_service_slugs, '{}')),
          'needs_verification', case when p_outcome = 'wrong_number' then 'phone' end
        )
    where id = owner_row.id;
  end if;

  insert into public.audit_events (actor_email, event_type, target_type, target_key, meta)
  values (
    lower(p_actor_email), 'contact_result_recorded', 'lead', target.name,
    jsonb_build_object('event_id', new_event_id, 'outcome', p_outcome, 'revision', new_revision)
  );

  result := jsonb_build_object(
    'event_id', new_event_id,
    'lead_name', target.name,
    'lead_status', p_lead_status,
    'lead_revision', new_revision,
    'assignment_id', owner_row.id,
    'assignment_status', case when owner_row.id is null then null else p_assignment_status end,
    'follow_up_at', assignment_due,
    'happened_at', happened,
    'actor_email', lower(p_actor_email)
  );
  insert into public.command_requests (idempotency_key, command, actor_email, request_hash, response)
  values (p_idempotency_key, 'record_contact_result', lower(p_actor_email), p_request_hash, result);
  return result || jsonb_build_object('replayed', false);
end;
$$;
revoke all on function public.record_contact_result(text, text, text, boolean, text, integer, text, text, timestamptz, text[], text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.record_contact_result(text, text, text, boolean, text, integer, text, text, timestamptz, text[], text, text, text, text)
  to service_role;

-- Readiness now also requires the contact command.
create or replace function public.schema_readiness()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'version', (select max(version) from public.schema_migrations),
    'checks', jsonb_build_object(
      'assign_lead_owner', to_regprocedure('public.assign_lead_owner(text,text,timestamptz,text,text,jsonb)') is not null,
      'claim_admin_search_jobs', to_regprocedure('public.claim_admin_search_jobs(integer)') is not null,
      'create_admin_search_job', to_regprocedure('public.create_admin_search_job(text,text,integer,boolean,text,text,integer,numeric,jsonb)') is not null,
      'check_login_rate_limit', to_regprocedure('public.check_login_rate_limit(text,integer,integer)') is not null,
      'record_login_attempt', to_regprocedure('public.record_login_attempt(text,boolean)') is not null,
      'record_contact_result', to_regprocedure('public.record_contact_result(text,text,text,boolean,text,integer,text,text,timestamptz,text[],text,text,text,text)') is not null,
      'one_active_owner_index', to_regclass('public.lead_assignments_one_active_owner_uidx') is not null,
      'idempotency_constraint', exists (
        select 1 from pg_constraint
        where conrelid = 'public.outreach_events'::regclass
          and conname = 'outreach_events_idempotency_key_key'
      ),
      'structured_outreach_columns', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'outreach_events' and column_name = 'follow_up_at'
      ),
      'lead_id_columns', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'lead_assignments' and column_name = 'lead_id'
      ),
      'lead_revision', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'leads' and column_name = 'revision'
      ),
      'lead_sources', to_regclass('public.lead_sources') is not null
    )
  );
$$;
revoke all on function public.schema_readiness() from public, anon, authenticated;
grant execute on function public.schema_readiness() to service_role;

insert into public.schema_migrations (version) values ('009') on conflict do nothing;
