"""Build supabase/schema.sql from the migration chain.

The migrations in supabase/migrations are the only hand-edited schema source.
schema.sql bundles them so a fresh project can be created with one paste into
the Supabase SQL editor. Every migration is idempotent, so the bundle is too.

    python scripts/build_schema.py          # rewrite schema.sql
    python scripts/build_schema.py --check  # fail if schema.sql is stale (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS_DIR = ROOT / "supabase" / "migrations"
OUTPUT = ROOT / "supabase" / "schema.sql"

HEADER = """\
-- Zeplin Lead System - full database schema.
--
-- GENERATED by scripts/build_schema.py from supabase/migrations. Do not edit
-- this file; add a new numbered migration and rebuild instead.
--
-- Fresh project: run this whole file once in the Supabase SQL editor.
-- Existing project: run the migrations you have not applied yet, in order.
-- Every statement is idempotent, so re-running is safe.
"""


def migrations() -> list[Path]:
    return sorted(MIGRATIONS_DIR.glob("[0-9][0-9][0-9]_*.sql"))


def render() -> str:
    parts = [HEADER]
    for path in migrations():
        body = path.read_text(encoding="utf-8").strip()
        parts.append(f"\n-- ===== {path.name} =====\n\n{body}\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if schema.sql is out of date")
    args = parser.parse_args()
    content = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print("supabase/schema.sql is out of date; run: python scripts/build_schema.py")
            return 1
        print("supabase/schema.sql is up to date.")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} from {len(migrations())} migrations.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
