-- Original Zeplin Lead System schema (commit 77e3843, May 2026).
-- Kept so the migration chain 001..N can build a database from scratch and
-- so upgrades can be tested from the very first deployed shape.


create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sector text,
  city text,
  category text,
  phone text,
  address text,
  rating numeric,
  review_count integer,
  maps_url text,
  website_url text,
  instagram_url text,
  score integer check (score between 0 and 100),
  grade text check (grade in ('A', 'B', 'C', 'D')),
  estimated_value_tl integer default 0,
  sales_priority_score integer check (sales_priority_score between 0 and 100),
  next_action text,
  priority_reason text,
  recommended_package jsonb not null default '{}'::jsonb,
  matched_services jsonb not null default '[]'::jsonb,
  data_quality jsonb not null default '{}'::jsonb,
  research_brief text,
  ai_report text,
  ai_email text,
  status text not null default 'yeni' check (status in ('yeni', 'contacted', 'converted')),
  last_analyzed text,
  raw jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_priority_idx on public.leads (sales_priority_score desc);
create index if not exists leads_score_idx on public.leads (score asc);
create index if not exists leads_sector_idx on public.leads (sector);
create index if not exists leads_status_idx on public.leads (status);
create index if not exists leads_raw_gin_idx on public.leads using gin (raw);

create table if not exists public.outreach_events (
  id bigint generated by default as identity primary key,
  lead_name text not null references public.leads(name) on delete cascade,
  action text not null,
  note text,
  happened_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists outreach_events_lead_idx on public.outreach_events (lead_name, happened_at desc);

create table if not exists public.pipeline_runs (
  id bigint generated by default as identity primary key,
  kind text not null,
  status text not null,
  message text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;
alter table public.outreach_events enable row level security;
alter table public.pipeline_runs enable row level security;

-- Service-role/secret-key backend sync bypasses RLS. Add anon policies later
-- only when the browser dashboard should read/write directly from Supabase.
