create table if not exists public.admin_search_jobs (
  id bigint generated by default as identity primary key,
  query text not null,
  city text not null,
  max_results integer not null default 10 check (max_results between 1 and 30),
  deep_research boolean not null default true,
  ai_mode text not null default 'smart' check (ai_mode in ('smart', 'flash', 'pro')),
  status text not null default 'queued' check (status in ('queued', 'running', 'success', 'failed')),
  created_by text,
  estimated_tokens integer not null default 0,
  estimated_cost_usd numeric not null default 0,
  result jsonb not null default '{}'::jsonb,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_search_jobs_status_idx
  on public.admin_search_jobs (status, created_at desc);

create table if not exists public.ai_token_ledger (
  id bigint generated by default as identity primary key,
  job_id bigint references public.admin_search_jobs(id) on delete set null,
  kind text not null default 'usage',
  provider text not null default 'deepseek',
  model text,
  estimated_tokens integer not null default 0,
  actual_tokens integer,
  estimated_cost_usd numeric not null default 0,
  actual_cost_usd numeric,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_token_ledger_job_idx
  on public.ai_token_ledger (job_id, created_at desc);

alter table public.admin_search_jobs enable row level security;
alter table public.ai_token_ledger enable row level security;

grant select, insert, update, delete on public.admin_search_jobs to service_role;
grant select, insert, update, delete on public.ai_token_ledger to service_role;

grant usage, select on sequence public.admin_search_jobs_id_seq to service_role;
grant usage, select on sequence public.ai_token_ledger_id_seq to service_role;
