do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select conname
    from pg_constraint
    where conrelid = 'public.leads'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%status%'
  loop
    execute format('alter table public.leads drop constraint if exists %I', constraint_name);
  end loop;
end $$;

alter table public.leads
  alter column status set default 'yeni';

alter table public.leads
  add constraint leads_status_check
  check (status in ('yeni', 'ready', 'missing_info', 'contacted', 'follow_up', 'converted', 'lost'));

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  role text not null default 'sales' check (role in ('admin', 'sales')),
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists app_users_role_idx
  on public.app_users (role, active);

create table if not exists public.lead_assignments (
  id bigint generated by default as identity primary key,
  lead_name text not null references public.leads(name) on delete cascade,
  user_email text not null references public.app_users(email) on delete cascade,
  status text not null default 'active' check (status in ('active', 'done', 'snoozed', 'archived')),
  due_at timestamptz,
  assigned_by text,
  assigned_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb,
  unique (lead_name, user_email)
);

create index if not exists lead_assignments_user_idx
  on public.lead_assignments (user_email, status, due_at);

create index if not exists lead_assignments_lead_idx
  on public.lead_assignments (lead_name, status);

alter table public.app_users enable row level security;
alter table public.lead_assignments enable row level security;

grant select, insert, update, delete on public.app_users to service_role;
grant select, insert, update, delete on public.lead_assignments to service_role;

grant usage, select on sequence public.app_users_id_seq to service_role;
grant usage, select on sequence public.lead_assignments_id_seq to service_role;
