-- Security, CRM ownership, idempotency and durable worker primitives.
-- Safe to run repeatedly in the Supabase SQL editor.

create extension if not exists pgcrypto;

alter table public.leads add column if not exists external_id text;

update public.leads
set external_id = case
  when coalesce(maps_url, raw->>'maps_url', '') <> ''
    then 'maps:' || encode(digest(coalesce(maps_url, raw->>'maps_url'), 'sha256'), 'hex')
  else 'name:' || encode(
    digest(lower(trim(name)) || '|' || lower(trim(coalesce(city, ''))), 'sha256'),
    'hex'
  )
end
where external_id is null;

alter table public.leads alter column external_id set not null;
create unique index if not exists leads_external_id_uidx on public.leads (external_id);

alter table public.outreach_events
  add column if not exists actor_email text,
  add column if not exists source text not null default 'dashboard',
  add column if not exists idempotency_key text;

create unique index if not exists outreach_events_idempotency_uidx
  on public.outreach_events (idempotency_key)
  where idempotency_key is not null;

create index if not exists outreach_events_actor_idx
  on public.outreach_events (actor_email, happened_at desc);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_email text,
  event_type text not null,
  target_type text not null,
  target_key text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_events_actor_idx
  on public.audit_events (actor_email, created_at desc);
create index if not exists audit_events_target_idx
  on public.audit_events (target_type, target_key, created_at desc);
alter table public.audit_events enable row level security;
grant select, insert on public.audit_events to service_role;
grant usage, select on sequence public.audit_events_id_seq to service_role;

create table if not exists public.auth_login_attempts (
  id bigint generated by default as identity primary key,
  key_hash text not null,
  attempted_at timestamptz not null default now()
);

create index if not exists auth_login_attempts_key_idx
  on public.auth_login_attempts (key_hash, attempted_at desc);
alter table public.auth_login_attempts enable row level security;
grant select, insert, delete on public.auth_login_attempts to service_role;
grant usage, select on sequence public.auth_login_attempts_id_seq to service_role;

create table if not exists public.ai_generations (
  id bigint generated by default as identity primary key,
  cache_key text not null unique,
  task text not null,
  provider text not null,
  model text not null,
  content text not null,
  usage jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ai_generations enable row level security;
grant select, insert, update, delete on public.ai_generations to service_role;
grant usage, select on sequence public.ai_generations_id_seq to service_role;

-- There can be only one current owner for a lead.
with ranked as (
  select id, row_number() over (
    partition by lead_name
    order by updated_at desc nulls last, id desc
  ) as position
  from public.lead_assignments
  where status = 'active'
)
update public.lead_assignments assignment
set status = 'archived', updated_at = now()
from ranked
where assignment.id = ranked.id and ranked.position > 1;

create unique index if not exists lead_assignments_one_active_owner_uidx
  on public.lead_assignments (lead_name)
  where status = 'active';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists ai_generations_set_updated_at on public.ai_generations;
create trigger ai_generations_set_updated_at before update on public.ai_generations
for each row execute function public.set_updated_at();

drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at before update on public.leads
for each row execute function public.set_updated_at();

drop trigger if exists app_users_set_updated_at on public.app_users;
create trigger app_users_set_updated_at before update on public.app_users
for each row execute function public.set_updated_at();

drop trigger if exists lead_assignments_set_updated_at on public.lead_assignments;
create trigger lead_assignments_set_updated_at before update on public.lead_assignments
for each row execute function public.set_updated_at();

drop trigger if exists admin_search_jobs_set_updated_at on public.admin_search_jobs;
create trigger admin_search_jobs_set_updated_at before update on public.admin_search_jobs
for each row execute function public.set_updated_at();

create or replace function public.create_admin_search_job(
  query text,
  city text,
  max_results integer,
  deep_research boolean,
  ai_mode text,
  created_by text,
  estimated_tokens integer,
  estimated_cost_usd numeric,
  reservation_meta jsonb default '{}'::jsonb
)
returns setof public.admin_search_jobs
language plpgsql
security definer
set search_path = public
as $$
#variable_conflict use_variable
declare
  created_job public.admin_search_jobs;
begin
  insert into public.admin_search_jobs (
    query, city, max_results, deep_research, ai_mode, created_by,
    estimated_tokens, estimated_cost_usd, meta
  ) values (
    query, city, max_results, deep_research, ai_mode, created_by,
    estimated_tokens, estimated_cost_usd, reservation_meta
  ) returning * into created_job;

  insert into public.ai_token_ledger (
    job_id, kind, provider, model, estimated_tokens, estimated_cost_usd, meta
  ) values (
    created_job.id, 'reservation', 'deepseek',
    reservation_meta->>'model_mix', estimated_tokens, estimated_cost_usd,
    jsonb_build_object('query', query, 'city', city, 'max_results', max_results)
  );

  return next created_job;
end;
$$;

create or replace function public.assign_lead_owner(
  target_lead_name text,
  target_user_email text,
  assignment_due_at timestamptz,
  assignment_by text,
  assignment_status text,
  assignment_meta jsonb default '{}'::jsonb
)
returns setof public.lead_assignments
language plpgsql
security definer
set search_path = public
as $$
declare
  assigned public.lead_assignments;
begin
  if assignment_status = 'active' then
    update public.lead_assignments
    set status = 'archived', updated_at = now()
    where lead_name = target_lead_name
      and status = 'active'
      and user_email <> lower(target_user_email);
  end if;

  insert into public.lead_assignments (
    lead_name, user_email, due_at, assigned_by, status, meta
  ) values (
    target_lead_name, lower(target_user_email), assignment_due_at,
    lower(assignment_by), assignment_status, assignment_meta
  )
  on conflict (lead_name, user_email) do update
  set due_at = excluded.due_at,
      assigned_by = excluded.assigned_by,
      status = excluded.status,
      meta = excluded.meta,
      updated_at = now()
  returning * into assigned;

  return next assigned;
end;
$$;

create or replace function public.claim_admin_search_jobs(job_limit integer default 1)
returns setof public.admin_search_jobs
language plpgsql
security definer
set search_path = public
as $$
begin
  -- A crashed worker may leave a job running. Retry it after one hour.
  update public.admin_search_jobs
  set status = 'queued',
      result = coalesce(result, '{}'::jsonb) || jsonb_build_object('recovered_at', now())
  where status = 'running' and updated_at < now() - interval '1 hour';

  return query
  with candidates as (
    select id
    from public.admin_search_jobs
    where status = 'queued'
    order by created_at asc
    for update skip locked
    limit greatest(1, least(job_limit, 10))
  )
  update public.admin_search_jobs jobs
  set status = 'running',
      result = coalesce(jobs.result, '{}'::jsonb) || jsonb_build_object('started_at', now())
  from candidates
  where jobs.id = candidates.id
  returning jobs.*;
end;
$$;

create or replace function public.check_login_rate_limit(
  attempt_key_hash text,
  attempt_limit integer default 8,
  window_seconds integer default 900
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  recent_attempts integer;
begin
  delete from public.auth_login_attempts
  where attempted_at < now() - interval '1 day';

  select count(*) into recent_attempts
  from public.auth_login_attempts
  where key_hash = attempt_key_hash
    and attempted_at >= now() - make_interval(secs => greatest(60, window_seconds));

  return recent_attempts >= greatest(1, attempt_limit);
end;
$$;

create or replace function public.record_login_attempt(
  attempt_key_hash text,
  attempt_succeeded boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if attempt_succeeded then
    delete from public.auth_login_attempts where key_hash = attempt_key_hash;
  else
    insert into public.auth_login_attempts (key_hash) values (attempt_key_hash);
  end if;
end;
$$;

revoke all on function public.create_admin_search_job(
  text, text, integer, boolean, text, text, integer, numeric, jsonb
) from public, anon, authenticated;
revoke all on function public.claim_admin_search_jobs(integer)
  from public, anon, authenticated;
grant execute on function public.create_admin_search_job(
  text, text, integer, boolean, text, text, integer, numeric, jsonb
) to service_role;
grant execute on function public.claim_admin_search_jobs(integer) to service_role;
revoke all on function public.assign_lead_owner(
  text, text, timestamptz, text, text, jsonb
) from public, anon, authenticated;
grant execute on function public.assign_lead_owner(
  text, text, timestamptz, text, text, jsonb
) to service_role;
revoke all on function public.check_login_rate_limit(text, integer, integer)
  from public, anon, authenticated;
revoke all on function public.record_login_attempt(text, boolean)
  from public, anon, authenticated;
grant execute on function public.check_login_rate_limit(text, integer, integer)
  to service_role;
grant execute on function public.record_login_attempt(text, boolean)
  to service_role;
