-- 011: AI generations tied to their input, one paid call per input, and a
-- per-call usage ledger.
--
-- * ai_generations rows now record what they were generated from
--   (input_hash, prompt_version, catalog_version, requested and actual model)
--   and a status. claim_ai_generation() turns the cache key into a lease, so
--   two requests for the same input make one provider call: the second one
--   gets the finished text, or "busy" while the first is still running.
-- * ai_token_ledger gets one 'usage' row per provider call (including empty
--   responses, failures and fallbacks) and per cache hit, with the token
--   split and the rates applied. A search job's 'reservation' is closed by a
--   'release' row, so open reservations and historical estimates are apart.
-- * ai_model_rates holds provider prices by model and start date. Rows are
--   entered by an admin from the provider's official price list; without a
--   row the code falls back to the DEEPSEEK_*_USD_PER_M_TOKENS settings and
--   records which source it used.
-- * ai_spend_summary() aggregates the whole ledger in the database.
--
-- Additive and idempotent; nothing is removed, so the connector can apply it.

alter table public.ai_generations add column if not exists lead_id bigint references public.leads(id) on delete set null;
alter table public.ai_generations add column if not exists input_hash text;
alter table public.ai_generations add column if not exists prompt_version text;
alter table public.ai_generations add column if not exists catalog_version text;
alter table public.ai_generations add column if not exists requested_model text;
alter table public.ai_generations add column if not exists status text not null default 'ready';
alter table public.ai_generations add column if not exists claimed_by text;
alter table public.ai_generations add column if not exists claimed_until timestamptz;
alter table public.ai_generations add column if not exists attempts integer not null default 0;
alter table public.ai_generations add column if not exists error text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.ai_generations'::regclass and conname = 'ai_generations_status_check'
  ) then
    alter table public.ai_generations
      add constraint ai_generations_status_check check (status in ('pending', 'ready', 'failed'));
  end if;
end;
$$;

create index if not exists ai_generations_lead_idx on public.ai_generations (lead_id, task);

alter table public.ai_token_ledger add column if not exists task text;
alter table public.ai_token_ledger add column if not exists cache_key text;
alter table public.ai_token_ledger add column if not exists lead_id bigint references public.leads(id) on delete set null;
alter table public.ai_token_ledger add column if not exists actor_email text;
alter table public.ai_token_ledger add column if not exists requested_model text;
alter table public.ai_token_ledger add column if not exists outcome text;
alter table public.ai_token_ledger add column if not exists prompt_tokens integer;
alter table public.ai_token_ledger add column if not exists cached_tokens integer;
alter table public.ai_token_ledger add column if not exists completion_tokens integer;
alter table public.ai_token_ledger add column if not exists rates jsonb;

create index if not exists ai_token_ledger_created_idx on public.ai_token_ledger (created_at desc);
create index if not exists ai_token_ledger_kind_idx on public.ai_token_ledger (kind, created_at desc);

create table if not exists public.ai_model_rates (
  id bigint generated by default as identity primary key,
  provider text not null,
  model text not null,
  effective_from date not null,
  input_usd_per_m numeric not null check (input_usd_per_m >= 0),
  cached_input_usd_per_m numeric not null check (cached_input_usd_per_m >= 0),
  output_usd_per_m numeric not null check (output_usd_per_m >= 0),
  source_note text,
  created_at timestamptz not null default now(),
  unique (provider, model, effective_from)
);

alter table public.ai_model_rates enable row level security;
grant select, insert, update on public.ai_model_rates to service_role;
grant usage, select on sequence public.ai_model_rates_id_seq to service_role;

-- Claim the generation for a cache key. Returns
--   {"status": "ready", "content", "provider", "model"}  finished earlier: use it;
--   {"status": "claimed"}                                 this caller generates;
--   {"status": "busy", "claimed_until"}                   someone else is generating.
-- A failed, expired or empty row is taken over.
create or replace function public.claim_ai_generation(
  p_cache_key text,
  p_task text,
  p_owner text,
  p_lease_seconds integer,
  p_provider text,
  p_requested_model text,
  p_lead_id bigint,
  p_input_hash text,
  p_prompt_version text,
  p_catalog_version text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed_id bigint;
  current_row public.ai_generations;
  lease interval := make_interval(secs => greatest(coalesce(p_lease_seconds, 180), 10));
begin
  insert into public.ai_generations (
    cache_key, task, provider, model, content, status, claimed_by, claimed_until, attempts,
    lead_id, input_hash, prompt_version, catalog_version, requested_model
  ) values (
    p_cache_key, p_task, p_provider, coalesce(p_requested_model, ''), '', 'pending', p_owner, now() + lease, 1,
    p_lead_id, p_input_hash, p_prompt_version, p_catalog_version, p_requested_model
  )
  on conflict (cache_key) do nothing
  returning id into claimed_id;
  if claimed_id is not null then
    return jsonb_build_object('status', 'claimed');
  end if;

  select * into current_row from public.ai_generations where cache_key = p_cache_key for update;
  if current_row.status = 'ready' and coalesce(current_row.content, '') <> '' then
    return jsonb_build_object(
      'status', 'ready', 'content', current_row.content,
      'provider', current_row.provider, 'model', current_row.model
    );
  end if;
  if current_row.status = 'pending'
     and current_row.claimed_until > now()
     and current_row.claimed_by is distinct from p_owner then
    return jsonb_build_object('status', 'busy', 'claimed_until', current_row.claimed_until);
  end if;

  update public.ai_generations
  set status = 'pending',
      claimed_by = p_owner,
      claimed_until = now() + lease,
      attempts = attempts + 1,
      error = null,
      lead_id = coalesce(p_lead_id, lead_id),
      input_hash = p_input_hash,
      prompt_version = p_prompt_version,
      catalog_version = p_catalog_version,
      requested_model = p_requested_model
  where id = current_row.id;
  return jsonb_build_object('status', 'claimed');
end;
$$;

-- Store the finished text. The first completion wins; a later one for an
-- already finished key changes nothing and returns false.
create or replace function public.complete_ai_generation(
  p_cache_key text,
  p_content text,
  p_provider text,
  p_model text,
  p_usage jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.ai_generations
  set status = 'ready', content = p_content, provider = p_provider, model = p_model,
      usage = coalesce(p_usage, '{}'::jsonb), claimed_by = null, claimed_until = null, error = null
  where cache_key = p_cache_key and status <> 'ready';
  return found;
end;
$$;

create or replace function public.fail_ai_generation(p_cache_key text, p_owner text, p_error text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.ai_generations
  set status = 'failed', error = left(p_error, 500), claimed_until = null
  where cache_key = p_cache_key and status = 'pending' and claimed_by = p_owner;
$$;

-- Whole-ledger totals; nothing is capped at the latest N rows.
create or replace function public.ai_spend_summary(p_today_start timestamptz default null)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with usage_rows as (
    select * from public.ai_token_ledger where kind = 'usage'
  ),
  reservations as (
    select job_id,
           sum(estimated_tokens) filter (where kind = 'reservation') as reserved_tokens,
           sum(estimated_cost_usd) filter (where kind = 'reservation') as reserved_usd,
           bool_or(kind = 'release') as released
    from public.ai_token_ledger
    where kind in ('reservation', 'release')
    group by job_id
  )
  select jsonb_build_object(
    'actual_cost_usd', coalesce((select round(sum(actual_cost_usd), 6) from usage_rows), 0),
    'actual_tokens', coalesce((select sum(actual_tokens) from usage_rows), 0),
    'provider_calls', (select count(*) from usage_rows where coalesce(outcome, 'success') <> 'cache_hit'),
    'cache_hits', (select count(*) from usage_rows where outcome = 'cache_hit'),
    'failed_calls', (select count(*) from usage_rows where outcome in ('error', 'empty')),
    'unpriced_calls', (select count(*) from usage_rows where actual_tokens > 0 and actual_cost_usd is null),
    'today_cost_usd', coalesce((
      select round(sum(actual_cost_usd), 6) from usage_rows
      where p_today_start is not null and created_at >= p_today_start
    ), 0),
    'active_reserved_tokens', coalesce((select sum(reserved_tokens) from reservations where not released), 0),
    'active_reserved_usd', coalesce((select round(sum(reserved_usd), 6) from reservations where not released), 0),
    'estimated_cost_usd', coalesce((select round(sum(reserved_usd), 6) from reservations), 0),
    'estimated_tokens', coalesce((select sum(reserved_tokens) from reservations), 0),
    'by_task', coalesce((
      select jsonb_object_agg(task_name, totals) from (
        select coalesce(task, 'unknown') as task_name,
               jsonb_build_object('calls', count(*), 'tokens', coalesce(sum(actual_tokens), 0),
                                  'cost_usd', coalesce(round(sum(actual_cost_usd), 6), 0)) as totals
        from usage_rows where coalesce(outcome, 'success') <> 'cache_hit'
        group by 1
      ) grouped
    ), '{}'::jsonb),
    'by_model', coalesce((
      select jsonb_object_agg(model_name, totals) from (
        select coalesce(model, 'unknown') as model_name,
               jsonb_build_object('calls', count(*), 'tokens', coalesce(sum(actual_tokens), 0),
                                  'cost_usd', coalesce(round(sum(actual_cost_usd), 6), 0)) as totals
        from usage_rows where coalesce(outcome, 'success') <> 'cache_hit'
        group by 1
      ) grouped
    ), '{}'::jsonb)
  );
$$;

revoke all on function public.claim_ai_generation(text,text,text,integer,text,text,bigint,text,text,text) from public;
revoke all on function public.complete_ai_generation(text,text,text,text,jsonb) from public;
revoke all on function public.fail_ai_generation(text,text,text) from public;
revoke all on function public.ai_spend_summary(timestamptz) from public;
grant execute on function public.claim_ai_generation(text,text,text,integer,text,text,bigint,text,text,text) to service_role;
grant execute on function public.complete_ai_generation(text,text,text,text,jsonb) to service_role;
grant execute on function public.fail_ai_generation(text,text,text) to service_role;
grant execute on function public.ai_spend_summary(timestamptz) to service_role;

create or replace function public.schema_readiness()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'version', (select max(version) from public.schema_migrations),
    'checks', jsonb_build_object(
      'assign_lead_owner', to_regprocedure('public.assign_lead_owner(text,text,timestamptz,text,text,jsonb)') is not null,
      'claim_admin_search_jobs', to_regprocedure('public.claim_admin_search_jobs(integer)') is not null,
      'create_admin_search_job', to_regprocedure('public.create_admin_search_job(text,text,integer,boolean,text,text,integer,numeric,jsonb)') is not null,
      'check_login_rate_limit', to_regprocedure('public.check_login_rate_limit(text,integer,integer)') is not null,
      'record_login_attempt', to_regprocedure('public.record_login_attempt(text,boolean)') is not null,
      'record_contact_result', to_regprocedure('public.record_contact_result(text,text,text,boolean,text,integer,text,text,timestamptz,text[],text,text,text,text)') is not null,
      'readable_leads', to_regprocedure('public.readable_leads(text)') is not null,
      'list_leads', to_regprocedure('public.list_leads(text,boolean,integer,bigint,integer,text,text)') is not null,
      'lead_activity_state', to_regclass('public.lead_activity_state') is not null,
      'one_active_owner_index', to_regclass('public.lead_assignments_one_active_owner_uidx') is not null,
      'idempotency_constraint', exists (
        select 1 from pg_constraint
        where conrelid = 'public.outreach_events'::regclass
          and conname = 'outreach_events_idempotency_key_key'
      ),
      'structured_outreach_columns', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'outreach_events' and column_name = 'follow_up_at'
      ),
      'lead_id_columns', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'lead_assignments' and column_name = 'lead_id'
      ),
      'lead_revision', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'leads' and column_name = 'revision'
      ),
      'lead_sources', to_regclass('public.lead_sources') is not null,
      'claim_ai_generation', to_regprocedure('public.claim_ai_generation(text,text,text,integer,text,text,bigint,text,text,text)') is not null,
      'ai_spend_summary', to_regprocedure('public.ai_spend_summary(timestamptz)') is not null,
      'ai_model_rates', to_regclass('public.ai_model_rates') is not null,
      'usage_ledger_columns', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'ai_token_ledger' and column_name = 'cached_tokens'
      )
    )
  );
$$;

insert into public.schema_migrations (version) values ('011') on conflict do nothing;
