-- Explicit commercial opportunities, separate from research readiness.
-- No historical leads are reclassified. One opportunity per lead in this release.
create table if not exists public.opportunities (
  id bigint generated by default as identity primary key,
  lead_id bigint not null unique references public.leads(id) on delete cascade,
  stage text not null default 'new' check(stage in ('new','contact','discovery','proposal','decision','won','lost')),
  revision integer not null default 0,
  service_slug text,
  amount numeric(14,2) check(amount is null or amount between 0.01 and 1000000000),
  amount_unknown boolean not null default true,
  currency text not null default 'TRY' check(currency='TRY'),
  lost_reason text,
  stage_entered_at timestamptz not null default now(),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((amount is null) = amount_unknown),
  check ((stage in ('won','lost')) = (closed_at is not null))
);
create table if not exists public.opportunity_history (
  id bigint generated by default as identity primary key,
  opportunity_id bigint not null references public.opportunities(id) on delete cascade,
  revision integer not null,
  from_stage text,
  to_stage text not null,
  actor_email text,
  source text not null,
  note text,
  amount numeric(14,2),
  amount_unknown boolean not null,
  service_slug text,
  cleared_contact_event_id bigint,
  happened_at timestamptz not null default now(),
  unique(opportunity_id,revision)
);
create index if not exists opportunity_history_lookup_idx on public.opportunity_history(opportunity_id,id desc);
alter table public.opportunities enable row level security;
alter table public.opportunity_history enable row level security;
revoke all on public.opportunities,public.opportunity_history from anon,authenticated;
grant select on public.opportunities,public.opportunity_history to service_role;
-- Writes are domain commands, history stays append-only for application clients.
revoke insert,update,delete on public.opportunities,public.opportunity_history from service_role;
grant usage,select on sequence public.opportunities_id_seq,public.opportunity_history_id_seq to service_role;

create or replace function public.opportunity_stage_rank(p_stage text)
returns integer language sql immutable set search_path=public as $$
 select array_position(array['new','contact','discovery','proposal','decision','won','lost'],p_stage);
$$;
revoke all on function public.opportunity_stage_rank(text) from public,anon,authenticated,service_role;

-- Shared transition used by the pipeline and contact-result trigger. The caller
-- locks the lead first. This helper is private (not a callable service-role RPC).
create or replace function public.apply_opportunity_transition(
 p_lead_id bigint,p_stage text,p_actor text,p_source text,p_note text,
 p_amount numeric,p_amount_unknown boolean,p_service text,p_expected integer
) returns public.opportunities language plpgsql security definer set search_path=public as $$
declare current_row public.opportunities; previous_stage text; created boolean:=false; happened timestamptz:=now();
begin
 if public.opportunity_stage_rank(p_stage) is null then
   raise exception using errcode='PT400',message='OPPORTUNITY_STAGE_INVALID';
 end if;
 if p_amount_unknown is null or (p_amount is null) <> p_amount_unknown
    or p_amount is not null and (p_amount<=0 or p_amount>1000000000 or p_amount<>round(p_amount,2)) then
   raise exception using errcode='PT400',message='OPPORTUNITY_AMOUNT_INVALID';
 end if;
 if length(coalesce(p_note,''))>2000 or length(coalesce(p_service,''))>80 then
   raise exception using errcode='PT400',message='OPPORTUNITY_DETAILS_INVALID';
 end if;
 select * into current_row from public.opportunities where lead_id=p_lead_id for update;
 if not found then
   if p_expected is not null and p_expected<>0 then
     raise exception using errcode='PT409',message='OPPORTUNITY_VERSION_CONFLICT';
   end if;
   insert into public.opportunities(lead_id) values(p_lead_id) returning * into current_row;
   created:=true;
 else
   if p_expected is not null and p_expected<>current_row.revision then
     raise exception using errcode='PT409',message='OPPORTUNITY_VERSION_CONFLICT';
   end if;
 end if;
 previous_stage:=case when created then null else current_row.stage end;
 if current_row.stage in ('won','lost') and p_stage<>current_row.stage and p_stage<>'new' then
   raise exception using errcode='PT409',message='OPPORTUNITY_REOPEN_REQUIRED';
 end if;
 if p_source='contact_result' and current_row.stage in ('won','lost') and p_stage<>current_row.stage then
   raise exception using errcode='PT409',message='OPPORTUNITY_REOPEN_REQUIRED';
 end if;
 if p_source='pipeline' and not created and public.opportunity_stage_rank(p_stage)<public.opportunity_stage_rank(current_row.stage)
    and nullif(trim(p_note),'') is null then
   raise exception using errcode='PT400',message='OPPORTUNITY_REASON_REQUIRED';
 end if;
 if p_stage='lost' and p_source='pipeline' and nullif(trim(p_note),'') is null then
   raise exception using errcode='PT400',message='OPPORTUNITY_REASON_REQUIRED';
 end if;
 if not created and current_row.stage=p_stage and current_row.amount is not distinct from p_amount
    and current_row.service_slug is not distinct from p_service
    and (p_stage<>'lost' or current_row.lost_reason is not distinct from nullif(trim(p_note),'')) then
   return current_row;
 end if;
 update public.opportunities set stage=p_stage,revision=revision+1,
   amount=p_amount,amount_unknown=p_amount_unknown,service_slug=p_service,
   lost_reason=case when p_stage='lost' then nullif(trim(p_note),'') end,
   stage_entered_at=case when stage<>p_stage or created then happened else stage_entered_at end,
   closed_at=case when p_stage in ('won','lost') then coalesce(closed_at,happened) end,
   updated_at=happened
 where id=current_row.id returning * into current_row;
 insert into public.opportunity_history(opportunity_id,revision,from_stage,to_stage,actor_email,source,note,amount,amount_unknown,service_slug,cleared_contact_event_id,happened_at)
 values(current_row.id,current_row.revision,previous_stage,p_stage,lower(p_actor),p_source,nullif(trim(p_note),''),p_amount,p_amount_unknown,p_service,
   case when p_stage in ('won','lost') or previous_stage in ('won','lost') then
     (select (latest_contact->>'id')::bigint from public.lead_activity_state where lead_id=p_lead_id) end,happened);
 if p_source<>'contact_result' then
   insert into public.outreach_events(lead_id,lead_name,action,actor_email,source,note,outcome,happened_at)
   select p_lead_id,name,'opportunity_stage_changed',lower(p_actor),p_source,nullif(trim(p_note),''),
     case when p_stage in ('won','lost') and previous_stage is distinct from p_stage then p_stage end,happened
   from public.leads where id=p_lead_id;
 end if;
 return current_row;
end;
$$;
revoke all on function public.apply_opportunity_transition(bigint,text,text,text,text,numeric,boolean,text,integer) from public,anon,authenticated,service_role;

create or replace function public.change_opportunity_stage(
 p_key text,p_hash text,p_actor text,p_is_admin boolean,p_lead_id bigint,
 p_expected_lead integer,p_expected_opportunity integer,p_stage text,p_note text,
 p_amount numeric,p_amount_unknown boolean,p_service text
) returns jsonb language plpgsql security definer set search_path=public as $$
declare target public.leads; owner_row public.lead_assignments; previous public.command_requests;
 opp public.opportunities; before_opp public.opportunities; answer jsonb; reopening boolean;
begin
 if p_key is null or p_key!~'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    or nullif(p_hash,'') is null or nullif(trim(p_actor),'') is null or p_expected_lead is null or p_expected_opportunity is null then
   raise exception using errcode='PT400',message='OPPORTUNITY_COMMAND_INVALID';
 end if;
 perform pg_advisory_xact_lock(hashtext('opportunity:'||p_key));
 select * into target from public.leads where id=p_lead_id for update;
 if not found then raise exception using errcode='PT404',message='LEAD_NOT_FOUND'; end if;
 select * into owner_row from public.lead_assignments where lead_id=target.id and status='active' for update;
 select * into previous from public.command_requests where idempotency_key=p_key;
 if found then
   -- Closing completes the assignment; its original owner can still replay
   -- the committed answer, until the lead is handed over to someone else.
   if not coalesce(p_is_admin,false) and not exists(select 1 from public.readable_leads(p_actor) r where r.lead_id=target.id) then
     raise exception using errcode='PT403',message='LEAD_NOT_ASSIGNED';
   end if;
   if previous.command<>'change_opportunity_stage' or previous.request_hash<>p_hash or lower(previous.actor_email)<>lower(p_actor)
      or (previous.response->'opportunity'->>'lead_id')::bigint<>target.id then
     raise exception using errcode='PT409',message='IDEMPOTENCY_KEY_REUSED';
   end if;
   return previous.response||jsonb_build_object('replayed',true);
 end if;
 if not coalesce(p_is_admin,false) and (owner_row.id is null or lower(owner_row.user_email)<>lower(p_actor)) then
   raise exception using errcode='PT403',message='LEAD_NOT_ASSIGNED';
 end if;
 if target.revision<>p_expected_lead then raise exception using errcode='PT409',message='LEAD_VERSION_CONFLICT'; end if;
 select * into before_opp from public.opportunities where lead_id=target.id for update;
 reopening:=before_opp.stage in ('won','lost') and p_stage='new';
 if (reopening or target.status in ('converted','lost') and before_opp.id is null)
    and (not coalesce(p_is_admin,false) or nullif(trim(p_note),'') is null) then
   raise exception using errcode='PT403',message='OPPORTUNITY_REOPEN_ADMIN_REQUIRED';
 end if;
 opp:=public.apply_opportunity_transition(target.id,p_stage,p_actor,'pipeline',p_note,p_amount,p_amount_unknown,p_service,p_expected_opportunity);
 -- This is a commercial transition, never a fabricated call/email/contact event.
 if opp.revision is distinct from before_opp.revision then
   update public.leads set
     status=case when p_stage='won' then 'converted' when p_stage='lost' then 'lost'
                 when reopening or status in ('converted','lost') then 'yeni' else status end,
     revision=revision+1 where id=target.id returning * into target;
   if p_stage in ('won','lost') then
     update public.lead_assignments set status='done',due_at=null,updated_at=now()
       where lead_id=target.id and status='active';
     update public.lead_activity_state set latest_follow_up_at=null where lead_id=target.id;
   end if;
   if reopening then
     -- Admin may reopen without inventing a next contact date or reassigning ownership.
     -- A fresh assignment is a separate explicit operation.
     update public.lead_activity_state set latest_follow_up_at=null where lead_id=target.id;
   end if;
   insert into public.audit_events(actor_email,event_type,target_type,target_key,meta)
   values(lower(p_actor),'opportunity_stage_changed','lead',target.name,
     jsonb_build_object('opportunity_id',opp.id,'from',before_opp.stage,'to',opp.stage,'revision',opp.revision));
 end if;
 answer:=jsonb_build_object('opportunity',to_jsonb(opp),'lead_revision',target.revision,'lead_status',target.status);
 insert into public.command_requests(idempotency_key,command,actor_email,request_hash,response)
 values(p_key,'change_opportunity_stage',lower(p_actor),p_hash,answer);
 return answer||jsonb_build_object('replayed',false);
end;
$$;
revoke all on function public.change_opportunity_stage(text,text,text,boolean,bigint,integer,integer,text,text,numeric,boolean,text) from public,anon,authenticated;
grant execute on function public.change_opportunity_stage(text,text,text,boolean,bigint,integer,integer,text,text,numeric,boolean,text) to service_role;

-- New contact results enter the same stage history in the existing transaction.
-- Existing timelines are intentionally not replayed or backfilled.
create or replace function public.contact_opportunity_transition()
returns trigger language plpgsql security definer set search_path=public as $$
declare next_stage text; current_row public.opportunities; detail text; plain jsonb;
begin
 if new.action<>'contact_result_recorded' or new.lead_id is null then return new; end if;
 perform 1 from public.leads where id=new.lead_id for update;
 select * into current_row from public.opportunities where lead_id=new.lead_id for update;
 next_stage:=case new.outcome when 'reached_interested' then 'discovery' when 'proposal_requested' then 'proposal'
   when 'won' then 'won' when 'lost' then 'lost' when 'not_interested' then 'lost'
   when 'no_answer' then 'contact' when 'reached_later' then 'contact' end;
 if next_stage is null then return new; end if;
 if next_stage not in ('won','lost') and current_row.stage not in ('won','lost')
    and public.opportunity_stage_rank(current_row.stage)>public.opportunity_stage_rank(next_stage) then
   next_stage:=current_row.stage;
 end if;
 detail:=new.note;
 if left(coalesce(detail,''),19)='ZEPLIN_ACTIVITY_V1:' then
   begin plain:=substring(detail from 20)::jsonb; detail:=plain->>'note';
   exception when invalid_text_representation then detail:=null; end;
 end if;
 perform public.apply_opportunity_transition(new.lead_id,next_stage,new.actor_email,'contact_result',left(detail,2000),
   current_row.amount,coalesce(current_row.amount_unknown,true),coalesce(current_row.service_slug,new.service_slugs[1]),null);
 return new;
end;
$$;
revoke all on function public.contact_opportunity_transition() from public,anon,authenticated,service_role;
create or replace trigger outreach_opportunity_transition after insert on public.outreach_events
for each row execute function public.contact_opportunity_transition();

-- A later note/manual verification rebuilds the activity projection. It must
-- not resurrect a contact's old cancelled follow-up after closing/reopening.
-- Event ids work even when several commands share the same transaction time.
create or replace function public.clear_opportunity_follow_up()
returns trigger language plpgsql security definer set search_path=public as $$
declare cancelled_id bigint;
begin
 if exists(select 1 from public.opportunities where lead_id=new.lead_id and stage in ('won','lost')) then
   new.latest_follow_up_at:=null;
 else
   select max(h.cleared_contact_event_id) into cancelled_id
   from public.opportunity_history h join public.opportunities o on o.id=h.opportunity_id
   where o.lead_id=new.lead_id;
   if cancelled_id is not null and (new.latest_contact->>'id')::bigint<=cancelled_id then
     new.latest_follow_up_at:=null;
   end if;
 end if;
 return new;
end;
$$;
revoke all on function public.clear_opportunity_follow_up() from public,anon,authenticated,service_role;
create or replace trigger activity_opportunity_follow_up before insert or update on public.lead_activity_state
for each row execute function public.clear_opportunity_follow_up();

-- Keep legacy status writes compatible without reopening a commercial deal
-- silently. Pipeline/contacts have already applied their transition before this.
create or replace function public.sync_opportunity_closed_status()
returns trigger language plpgsql security definer set search_path=public as $$
declare opp public.opportunities; next_stage text;
begin
 if new.status is not distinct from old.status then return new; end if;
 select * into opp from public.opportunities where lead_id=new.id for update;
 if opp.id is null then return new; end if;
 next_stage:=case new.status when 'converted' then 'won' when 'lost' then 'lost' end;
 if next_stage is not null and opp.stage<>next_stage then
   perform public.apply_opportunity_transition(new.id,next_stage,null,'legacy_status',null,opp.amount,opp.amount_unknown,opp.service_slug,null);
 end if;
 if next_stage is null and opp.stage in ('won','lost') then
   raise exception using errcode='PT409',message='OPPORTUNITY_REOPEN_REQUIRED';
 end if;
 if next_stage is not null then
   update public.lead_assignments set status='done',due_at=null,updated_at=now() where lead_id=new.id and status='active';
   update public.lead_activity_state set latest_follow_up_at=null where lead_id=new.id;
 end if;
 return new;
end;
$$;
revoke all on function public.sync_opportunity_closed_status() from public,anon,authenticated,service_role;
create or replace trigger leads_opportunity_closed_status after update of status on public.leads
for each row execute function public.sync_opportunity_closed_status();

create or replace function public.list_opportunities(p_actor text,p_is_admin boolean)
returns jsonb language sql stable security definer set search_path=public as $$
 select coalesce(jsonb_agg(to_jsonb(opp)||jsonb_build_object(
  'lead_name',lead.name,'lead_revision',lead.revision,'lead_status',lead.status,
  'owner_email',owner_row.user_email,'due_at',case when owner_row.status='active' then owner_row.due_at end,
  'last_contact_at',state.latest_contact_at,
  'can_write',p_is_admin or (owner_row.status='active' and lower(owner_row.user_email)=lower(p_actor))
 ) order by opp.stage_entered_at,opp.id),'[]'::jsonb)
 from public.opportunities opp join public.leads lead on lead.id=opp.lead_id
 left join lateral(select a.* from public.lead_assignments a where a.lead_id=lead.id
   and a.status in ('active','done','snoozed') order by (a.status='active') desc,a.updated_at desc,a.id desc limit 1) owner_row on true
 left join public.lead_activity_state state on state.lead_id=lead.id
 where p_is_admin or exists(select 1 from public.readable_leads(p_actor) readable where readable.lead_id=lead.id);
$$;
revoke all on function public.list_opportunities(text,boolean) from public,anon,authenticated;
grant execute on function public.list_opportunities(text,boolean) to service_role;

create or replace function public.read_opportunity_history(p_actor text,p_is_admin boolean,p_lead_id bigint,p_before bigint,p_limit integer)
returns jsonb language sql stable security definer set search_path=public as $$
 select coalesce(jsonb_agg(to_jsonb(rows) order by rows.id desc),'[]'::jsonb) from (
  select history.* from public.opportunity_history history join public.opportunities opp on opp.id=history.opportunity_id
  where opp.lead_id=p_lead_id and (p_before is null or history.id<p_before)
    and (p_is_admin or exists(select 1 from public.readable_leads(p_actor) readable where readable.lead_id=opp.lead_id))
  order by history.id desc limit greatest(1,least(coalesce(p_limit,50),100))
 ) rows;
$$;
revoke all on function public.read_opportunity_history(text,boolean,bigint,bigint,integer) from public,anon,authenticated;
grant execute on function public.read_opportunity_history(text,boolean,bigint,bigint,integer) to service_role;

-- Extra readiness is additive: do not replace 012's worker checks when both
-- packages are installed. The application combines both RPCs.
create or replace function public.opportunity_schema_readiness()
returns jsonb language sql stable security definer set search_path=public as $$
 select jsonb_build_object(
  'opportunities',to_regclass('public.opportunities') is not null,
  'opportunity_history',to_regclass('public.opportunity_history') is not null,
  'opportunity_command',to_regprocedure('public.change_opportunity_stage(text,text,text,boolean,bigint,integer,integer,text,text,numeric,boolean,text)') is not null,
  'opportunity_contact_trigger',exists(select 1 from pg_trigger where tgrelid='public.outreach_events'::regclass and tgname='outreach_opportunity_transition'),
  'opportunity_status_trigger',exists(select 1 from pg_trigger where tgrelid='public.leads'::regclass and tgname='leads_opportunity_closed_status')
  ,'opportunity_follow_up_trigger',exists(select 1 from pg_trigger where tgrelid='public.lead_activity_state'::regclass and tgname='activity_opportunity_follow_up')
 );
$$;
revoke all on function public.opportunity_schema_readiness() from public,anon,authenticated;
grant execute on function public.opportunity_schema_readiness() to service_role;
insert into public.schema_migrations(version) values('013') on conflict do nothing;
